### PR TITLE
Fix colormap bug when ploting phantom maps

### PR DESCRIPTION
**Pull request by beorostica**
This pull request is meant to addres #328

### CODE REVIEW

**Comment by cncastillo** [comment]
Are you sure this works? show me an example with and without `cmin` and `cmax`.

**Comment by beorostica** [comment]
There you go!

image

**Comment by cncastillo** [comment]
`cmin` and `cmax` are not in the same units as the plots, try `cmax=2500`

**Comment by beorostica** [comment]
Originally, it was meant to receive seconds (ex: cmax=2.5):
image

**Comment by cncastillo** [comment]
Look at the tooltip and the colorbar.

**Comment by cncastillo** [comment]
Hi Boris, can you show more examples for T1, T2, dw, etc?

**Comment by beorostica** [comment]
It's looking good!
```julia
julia> plot_phantom_map(obj, :ρ; view_2d=true)
julia> plot_phantom_map(obj, :ρ; view_2d=true, cmin=0.5, cmax=1.5)

julia> plot_phantom_map(obj, :T1; view_2d=true)
julia> plot_phantom_map(obj, :T1; view_2d=true, cmin=500, cmax=3000)

julia> plot_phantom_map(obj, :T2; view_2d=true)
julia> plot_phantom_map(obj, :T2; view_2d=true, cmin=100, cmax=200)

julia> plot_phantom_map(obj, :T2s; view_2d=true)
julia> plot_phantom_map(obj, :T2s; view_2d=true, cmin=20, cmax=200)

julia> plot_phantom_map(obj, :Δw; view_2d=true)
julia> plot_phantom_map(obj, :Δw; view_2d=true, cmin=-500, cmax=-50)
```
image

**Comment by cncastillo** [comment]
Ok, it looks good! Do we need to bump KomaMRIPlots?

**Comment by beorostica** [comment]
The actual version in the JuliaRegistries is "0.8.1" and the version in the Project.toml "0.8.1" too. So, it is necessary an update.

**Review by cncastillo — APPROVED** [review]

**Pull request merged**
