### PR TITLE
Remove deprecation warning for sort function

### PR DESCRIPTION
**Pull request by beorostica**
This pull request is meant to address #326.

### CODE REVIEW

**Comment by cncastillo** [comment]
It is not passing any of the tests. Remember that `function!` is an in-place operation, and does not necessarily return an output.

**Comment by cncastillo** [comment]
Does the sorting have any effect? For example, on `seq.DEF` or `seq.DEF["extensions"]`

**Comment by beorostica** [comment]
I read the code, and in all cases, the xxxLibrary dictionaries are indexed by keys, which is the correct method for accessing dictionaries in Julia (as opposed to by their positions, for which an OrderedDict should be used).

It is important to note that the xxxLibrary dictionaries contain ID numbers in their keys (the IDs defined in the pulseq file). When we use other functions to filter by ID, we access that ID in the xxxLibrary dictionary.

I visually inspected some .seq files, and I did not observe any differences. It's a good idea to add automated tests with a defined ground truth for this purpose.

I used the .seq example in #73, which includes extensions, and again, I did not observe any differences.

**Comment by cncastillo** [comment]
That does not an answer my question.

**Comment by beorostica** [comment]
Here for seq.DEF and seq.DEF["extension"]:
```julia
julia> seq_sorted.DEF
Dict{String, Any} with 15 entries:
  "signature"                => "8c6b75007aa328b27fe3688911ce4a9b"
  "AdcRasterTime"            => 1.0e-7
  "GradientRasterTime"       => 1.0e-5
  "TotalDuration"            => 9.75
  "FOV"                      => [0.256, 0.256, 0.005]
  "Name"                     => "cine-gre"
  "Nz"                       => 1
  "Nx"                       => 128
  "Ny"                       => 1080
  "PulseqVersion"            => 1004000
  "BlockDurationRaster"      => 1.0e-5
  "extension"                => [1, 2, 0, 0, 0, 0, 2, 0, 0, 0  …  2, 0, 0, 0, 0, 2, 0, 0, 0, 0]
  "FileName"                 => "cine_gre.seq"
  "additional_text"          => "# Format of extension lists:\n# id type ref next_id\n# next_id of 0 terminates the list\n# Ext…"  "RadiofrequencyRasterTime" => 1.0e-6

julia> seq_unsorted.DEF
Dict{String, Any} with 15 entries:
  "signature"                => "8c6b75007aa328b27fe3688911ce4a9b"
  "AdcRasterTime"            => 1.0e-7
  "GradientRasterTime"       => 1.0e-5
  "TotalDuration"            => 9.75
  "FOV"                      => [0.256, 0.256, 0.005]
  "Name"                     => "cine-gre"
  "Nz"                       => 1
  "Nx"                       => 128
  "Ny"                       => 1080
  "PulseqVersion"            => 1004000
  "BlockDurationRaster"      => 1.0e-5
  "extension"                => [1, 2, 0, 0, 0, 0, 2, 0, 0, 0  …  2, 0, 0, 0, 0, 2, 0, 0, 0, 0]
  "FileName"                 => "cine_gre.seq"
  "additional_text"          => "# Format of extension lists:\n# id type ref next_id\n# next_id of 0 terminates the list\n# Ext…"  "RadiofrequencyRasterTime" => 1.0e-6

julia> seq_sorted.DEF["extension"] == seq_unsorted.DEF["extension"]
true
```

**Comment by cncastillo** [comment]
Perfect, this is what I wanted to see. Please bump KomaMRIFiles's version, and I will merge this PR.

**Pull request merged**
